server:
  port: 8080

spring:
  profiles:
    active: dev

---

spring:
  config:
    activate:
      on-profile: dev
api:
  dummyjson:
    url: https://dummyjson.com/products

---

spring:
  config:
    activate:
      on-profile: prod
api:
  dummyjson:
    url: https://dummyjson.com/products
